### ISSUE TITLE
Load latest Wikidata dump in Blazegraph

### ISSUE THREAD

**Issue by thewillyhuman** [weso/weso-scholia#7]
To load the latest Wikidata dump in a local Blazegraph first we need to download and extract the latest dump. This is giving some headaches as the size is very big. 1,5Tb for the Turtle and more than 2Tb for the turtle file. Therefore with the currently available hardware, we are not able to extract the n-triples dump.

Next, we will start research to try to estimate the total amount of storage space needed.

**Comment by thewillyhuman** [comment]
The latest dump can be found at `/vault/projects/weso-scholia/dumps/latests-all.nt`. When loading it in Blazegraph the following error raises:
```
ERROR: uri=[file:/data/latest-all.nt], context-uri=[]
java.util.concurrent.ExecutionException: org.openrdf.rio.RDFParseException: Expected a letter, found: 8 [line 2346]
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.bigdata.rdf.sail.webapp.BigdataServlet.submitApiTask(BigdataServlet.java:294)
	at com.bigdata.rdf.sail.webapp.InsertServlet.doPostWithURIs(InsertServlet.java:400)
	at com.bigdata.rdf.sail.webapp.InsertServlet.doPost(InsertServlet.java:119)
	at com.bigdata.rdf.sail.webapp.RESTServlet.doPost(RESTServlet.java:303)
	at com.bigdata.rdf.sail.webapp.MultiTenancyServlet.doPost(MultiTenancyServlet.java:195)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:873)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1623)
	at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:214)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:540)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1700)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1345)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1667)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1247)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:220)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:152)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:505)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:370)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:267)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:698)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:804)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.openrdf.rio.RDFParseException: Expected a letter, found: 8 [line 2346]
	at org.openrdf.rio.helpers.RDFParserHelper.reportError(RDFParserHelper.java:348)
	at org.openrdf.rio.helpers.RDFParserBase.reportError(RDFParserBase.java:608)
	at org.openrdf.rio.ntriples.NTriplesParser.reportError(NTriplesParser.java:596)
	at org.openrdf.rio.ntriples.NTriplesParser.parseNodeID(NTriplesParser.java:455)
	at org.openrdf.rio.ntriples.NTriplesParser.parseObject(NTriplesParser.java:391)
	at org.openrdf.rio.ntriples.NTriplesParser.parseTriple(NTriplesParser.java:290)
	at org.openrdf.rio.ntriples.NTriplesParser.parse(NTriplesParser.java:193)
	at org.openrdf.rio.ntriples.NTriplesParser.parse(NTriplesParser.java:132)
	at com.bigdata.rdf.sail.webapp.InsertServlet$InsertWithURLsTask.call(InsertServlet.java:569)
	at com.bigdata.rdf.sail.webapp.InsertServlet$InsertWithURLsTask.call(InsertServlet.java:417)
	at com.bigdata.rdf.task.ApiTaskForIndexManager.call(ApiTaskForIndexManager.java:68)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	... 1 more
```

By means of `sed -n 2346p /vault/projects/weso-scholia/dumps/latest-all.nt ` we access the triple that is generating the error and found `<http://www.wikidata.org/entity/Q31> <http://www.wikidata.org/prop/direct/P1589> _:8e6c62af66fd3ec3edcc5766e385d566 .`. It is relevant that the problem is located at the anonymous node. And, if we use the command `grep -n -m 2 _: /vault/projects/weso-scholia/dumps/latest-all.nt` we find that the error raises at the very first appearance of this type of nodes.

**Comment by DaniFdezAlvarez** [comment]
I found this... it doesnt seem promising:  https://github.com/blazegraph/database/issues/5

**Comment by DaniFdezAlvarez** [comment]
Python script for splittign the original file sinto smaller chunks and rename the bnodes, so they do not start with a number. 
WARNING: the split destroys the original file. But I guess thats the only way if we do not have memory enough to hold a complete corrected copy of that file. The only content duplicated in disk during execution time will be the number of lines of a chunk AS soon as the chunk is written, the corresponding part of the original file is erased.

```python

# from shutil import copyfile
from time import time

# copyfile("toy.txt", "toy2.txt")

TARGET_FILE = "toy2.txt"  # Original file path
TEMPLATE_FILE = "chunk{}.nt"  # template to place the parts of the original file in disk
CHUNK_MAX_LINES = 3  # Max size (in number of lines) of each chunk


## clean_line() consts
_TARGET_INDEXES = [0,2]
_TARGET_PREFIX_BNODE = "_:"
_NEW_PREFIX_BNODE = "_:n"
_SEP = " "
_MIN_NUMBER_OF_PIECES_LINE_WITH_A_TRIPLE = 3

def clean_line(target_line):
    pieces = target_line.split(_SEP)
    if len(pieces) < _MIN_NUMBER_OF_PIECES_LINE_WITH_A_TRIPLE:
        return target_line
    modification = False
    for an_index in _TARGET_INDEXES:
        if pieces[an_index].startswith(_TARGET_PREFIX_BNODE):
            pieces[an_index] = _NEW_PREFIX_BNODE + pieces[an_index][2:]
            modification = True
    return target_line if not modification else _SEP.join(pieces)

def write_chunk(a_point, countdown, target_file, dest_template):
    with open(target_file, "r") as f_in:
        f_in.seek(a_point)
        with open(dest_template.format(countdown), "w") as f_out:
            for a_line in f_in:
                f_out.write(clean_line(a_line))

def truncate_file(a_point):
    with open(TARGET_FILE, "a") as f_in:
        f_in.seek(a_point)
        f_in.truncate()

def find_offset_points(target_file, lines_per_chunk):
    offset_points = [0]
    tmp_div = 0
    counter = 0
    with open(target_file, "rb") as f:
        for _ in f:
            counter += 1
            if counter / lines_per_chunk > tmp_div:
                tmp_div += 1
                offset_points.append(f.tell())
    return offset_points

def run(target_file, lines_per_chunk, dest_template):
    offset_points = find_offset_points(target_file, lines_per_chunk)
    ini = time()
    for i in reversed(range(len(offset_points))):
        print("Going for a chunk! Countdown: {}".format(i))
        a_point = offset_points[i]
        write_chunk(a_point=a_point,
                    countdown=i,
                    target_file=target_file,
                    dest_template=dest_template)
        truncate_file(a_point)
        print("Chunk finished! Seconds since init process: {}".format(time() - ini))

if __name__ == "__main__":
    run(target_file=TARGET_FILE,
        lines_per_chunk=CHUNK_MAX_LINES,
        dest_template=TEMPLATE_FILE)
    print("Done!")

```

**Comment by thewillyhuman** [comment]
| Action: | Deploy a local Wikidata Instance | 
| ------ | -------- |
| **Reproducibility:** | 4/5 |
| **Time:** | 5-6 days |
| **Resources:** | 16 Cores, 100 Gb Memory, 1Tb Disk and Ethernet |
| **O.S.:** | Rocky Linux (RHEL) |
| **Source:** | [https://addshore.com/2019/10/your-own-wikidata-query-service-with-no-limits/](https://addshore.com/2019/10/your-own-wikidata-query-service-with-no-limits/) |

## 1. Install Docker
This tutorial mainly makes use of the docker tool to extract, transform and load the data into our local Wikibase instance.

In order to install Docker in Rocky Linux (RHEL) or any other similar flavor, like CentOS we have to follow these steps:

### 1.1. Remove any prior installations of docker components
```bash
sudo yum remove docker \
                  docker-client \
                  docker-client-latest \
                  docker-common \
                  docker-latest \
                  docker-latest-logrotate \
                  docker-logrotate \
                  docker-engine
```

### 1.2. Install yum-utils and add the Docker repository
```bash
sudo yum install -y yum-utils

sudo yum-config-manager \
    --add-repo \
    https://download.docker.com/linux/centos/docker-ce.repo
```

### 1.3. Install Docker Engine
```bash
sudo yum install docker-ce docker-ce-cli containerd.io
```

### 1.4. Start and enable Docker daemon
```bash
sudo systemctl start docker
sudo systemctl enable docker
```

### 1.5. Post-Installation Steps
Once Docker is installed in our system we can left the installation here. The problem is that now in order to run any Docker command we will need to provide the `sudo` order. To skip this we just need to add our user or any user in the machine to the docker group. To do this:

```bash
sudo usermod -aG docker $USER
```

## 2. Download latest Wikidata TTL dump
We, the WESO Research Group, provide a docker image that autamatically downloads the latests ttl dump. For that, first you will need to create a directory on your machine where you will work. Notice that this directory will need at leats 1Tb of space. Then:

```bash
docker run -d -v <local-work-dir>:/jobdir wesogroup/wd-dump-download-json-job
```

The `-d` arguments detaches the container execution from the shell. So you can disconnect without stoping the dump download. **This should take from 30 minutes to 1h.** To check the status you can execute `docker ps`, copy the id of the container and the `docker logs <container-id>`.

## 3. Munge the data
Next step is to munge the data. This will split the original dump file in chunks so it can be processed easier. This is also executed within a Docker container wo you don't have to install anything.

```bash
docker run \
  --entrypoint=/bin/bash \
  -d \
  -v <local-work-dir>:/stuff \
  wikibase/wdqs:0.3.6 \
  ./munge.sh \
  -c 50000 \
  -f /stuff/latest-all.ttl.gz \
  -d /stuff/mungeOut
```

**This will execute for at least 20-24 hours.** The current state can be explored over `docker logs <container-id>` command.

## 4. Deploy Wikidata Query Service
In order to populate the service we first need to run it using the below command. This mounts the directory containing the munged data as well as the directory for storing the service JNL file in. This will also expose the service on port 9999 which will be writable, so if you don’t want other people to access this check your firewall rules. Don’t worry if you don’t have a dockerData directory, as it will be created when you run this command.

```bash
docker run --entrypoint=/runBlazegraph.sh -d \
  -v <local-work-dir>/dockerData:/wdqs/data \
  -v <local-work-dir>:/mnt/disks/ssddata \
  -e HEAP_SIZE="128g" \
  -p 9999:9999 wikibase/wdqs:0.3.6
```

## 5. Load the data
Now we will load the data. For it we need the ID of the Docker container. This can be obtained by means of the `docker ps` command. Then:

```bash
docker exec -it <contianer-id> bash
```

And, once inside:

```bash
/wdqs/loadData.sh -n wdq -d <local-work-dir>/mungeOut
```

This step might take up to 5 days. So please run it so you can detach form the container at any point without stopping the execution.

Once the the data appears to be loaded, you can try out a shorter version of the cats query from the service examples.

```bash
curl localhost:9999/bigdata/namespace/wdq/sparql?query=%23Cats%0ASELECT%20%3Fitem%20%3FitemLabel%20%0AWHERE%20%0A%7B%0A%20%20%3Fitem%20wdt%3AP31%20wd%3AQ146.%0A%20%20SERVICE%20wikibase%3Alabel%20%7B%20bd%3AserviceParam%20wikibase%3Alanguage%20%22en%2Cen%22.%20%7D%0A%7D
```
